/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminBinaryRouteImport } from './routes/admin-binary'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiPublicNotifyTelegramRouteImport } from './routes/api/public/notify-telegram'

const AdminBinaryRoute = AdminBinaryRouteImport.update({
  id: '/admin-binary',
  path: '/admin-binary',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicNotifyTelegramRoute = ApiPublicNotifyTelegramRouteImport.update({
  id: '/api/public/notify-telegram',
  path: '/api/public/notify-telegram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-binary': typeof AdminBinaryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/notify-telegram': typeof ApiPublicNotifyTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-binary': typeof AdminBinaryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/notify-telegram': typeof ApiPublicNotifyTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-binary': typeof AdminBinaryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/notify-telegram': typeof ApiPublicNotifyTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-binary'
    | '/admin/login'
    | '/admin/'
    | '/api/public/notify-telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-binary'
    | '/admin/login'
    | '/admin'
    | '/api/public/notify-telegram'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-binary'
    | '/admin/login'
    | '/admin/'
    | '/api/public/notify-telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminBinaryRoute: typeof AdminBinaryRoute
  ApiPublicNotifyTelegramRoute: typeof ApiPublicNotifyTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin-binary': {
      id: '/admin-binary'
      path: '/admin-binary'
      fullPath: '/admin-binary'
      preLoaderRoute: typeof AdminBinaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/notify-telegram': {
      id: '/api/public/notify-telegram'
      path: '/api/public/notify-telegram'
      fullPath: '/api/public/notify-telegram'
      preLoaderRoute: typeof ApiPublicNotifyTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminBinaryRoute: AdminBinaryRoute,
  ApiPublicNotifyTelegramRoute: ApiPublicNotifyTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
